import SwiftUIpublic class DSCoreLight{


    --color_accent_bg..base("#265BD9")
    --color_accent_disabled..base("#577EDB")
    --color_accent_fr_c_1..base("#577EDB")
    --color_accent_fr_c_2..base("#AABADF")
    --color_accent_fr_c_3..base("#DCE2EF")
    --color_accent_fr_disabled..base("#193476")
    --color_accent_hover..base("#2252C3")
    --color_accent_2_bg..base("#262626")
    --color_accent_2_disabled..base("#424242")
    --color_accent_2_fr_c_1..base("#424242")
    --color_accent_2_fr_c_2..base("#707070")
    --color_accent_2_fr_c_3..base("#E6E6E6")
    --color_accent_2_fr_disabled..base("#8F8F8F")
    --color_accent_2_hover..base("#2E2E2E")
    --color_brand_bg..base("#FF5B5A")
    --color_brand_disabled..base("#E68A89")
    --color_brand_fr_c_1..base("#D24141")
    --color_brand_fr_c_2..base("#8E1110")
    --color_brand_fr_c_3..base("#600606")
    --color_brand_fr_disabled..base("#8C3736")
    --color_brand_hover..base("#F53E3D")
    --color_danger_bg..base("#D52A2A")
    --color_danger_disabled..base("#E16666")
    --color_danger_fr_c_1..base("#E16666")
    --color_danger_fr_c_2..base("#F2BBBB")
    --color_danger_fr_c_3..base("#FEF0F0")
    --color_danger_fr_disabled..base("#5C3737")
    --color_danger_hover..base("#A52727")
    --color_low_bg..base("#FEC113")
    --color_low_disabled..base("#CCB77A")
    --color_low_fr_c_1..base("#CE9E12")
    --color_low_fr_c_2..base("#8A6C15")
    --color_low_fr_c_3..base("#695311")
    --color_low_fr_disabled..base("#766228")
    --color_low_hover..base("#DAA40C")
    --color_neutral_bg..base("#FAFAFA")
    --color_neutral_fr_accent_c_1..base("#C4CDE3")
    --color_neutral_fr_accent_c_2..base("#6C8EE0")
    --color_neutral_fr_accent_c_3..base("#265BD9")
    --color_neutral_fr_c_1..base("#CFCFCF")
    --color_neutral_fr_c_2..base("#919191")
    --color_neutral_fr_c_3..base("#737373")
    --color_neutral_fr_c_4..base("#4C4E52")
    --color_neutral_fr_c_5..base("#262222")
    --color_neutral_fr_danger_c_1..base("#E9C4C4")
    --color_neutral_fr_danger_c_2..base("#D17575")
    --color_neutral_fr_danger_c_3..base("#D52A2A")
    --color_neutral_fr_success_c_1..base("#B2D7C2")
    --color_neutral_fr_success_c_2..base("#27A55D")
    --color_neutral_fr_success_c_3..base("#318153")
    --color_neutral_1_bg..base("#FFFFFF")
    --color_neutral_1_fr_c_0125..base("#E5E5E6")
    --color_neutral_1_fr_c_1..base("#D0D2D8")
    --color_neutral_1_fr_c_2..base("#949494")
    --color_neutral_1_fr_c_3..base("#74767B")
    --color_neutral_1_fr_c_4..base("#4E5055")
    --color_neutral_1_fr_c_5..base("#252628")
    --color_neutral_2_bg..base("#EBEBEB")
    --color_neutral_2_fr_c_1..base("#C2C2C2")
    --color_neutral_2_fr_c_2..base("#878787")
    --color_neutral_2_fr_c_3..base("#696A6D")
    --color_neutral_2_fr_c_4..base("#43454C")
    --color_neutral_2_fr_c_5..base("#161718")
    --color_neutral_3_bg..base("#D9D9D9")
    --color_neutral_3_fr_c_1..base("#B1B2B4")
    --color_neutral_3_fr_c_2..base("#787A7D")
    --color_neutral_3_fr_c_3..base("#5B5E62")
    --color_neutral_3_fr_c_4..base("#383A3D")
    --color_neutral_3_fr_c_5..base("#18191B")
    --color_overlay_bg..base("#00000066")
    --color_success_bg..base("#29A35C")
    --color_success_disabled..base("#7AB894")
    --color_success_fr_c_1..base("#178244")
    --color_success_fr_c_2..base("#134E2C")
    --color_success_fr_c_3..base("#092F18")
    --color_success_fr_disabled..base("#326246")
    --color_success_hover..base("#26824C")
    --color_warning_bg..base("#F38B16")
    --color_warning_disabled..base("#D19C61")
    --color_warning_fr_c_1..base("#CA6C02")
    --color_warning_fr_c_2..base("#7F480A")
    --color_warning_fr_c_3..base("#57330A")
    --color_warning_fr_disabled..base("#794A16")
    --color_warning_hover..base("#D67200")
    --ios_16_card..base("#A2A2A2")
    --ios_16_theme..base("#000000")
    --palette_black..base("#000000")
    --palette_blue_100..base("#D6DFF5")
    --palette_blue_200..base("#C2CFF0")
    --palette_blue_300..base("#99AFE5")
    --palette_blue_400..base("#7090DB")
    --palette_blue_50..base("#EBEFFA")
    --palette_blue_500..base("#446DD0")
    --palette_blue_600..base("#294DA3")
    --palette_blue_700..base("#1A3066")
    --palette_blue_800..base("#0F1D3D")
    --palette_blue_900..base("#0A1329")
    --palette_blue_2_100..base("#D4EEF7")
    --palette_blue_2_200..base("#BEE6F3")
    --palette_blue_2_300..base("#93D5EB")
    --palette_blue_2_400..base("#68C5E2")
    --palette_blue_2_50..base("#E8F7FB")
    --palette_blue_2_500..base("#26A5CF")
    --palette_blue_2_600..base("#1B708D")
    --palette_blue_2_700..base("#104556")
    --palette_blue_2_800..base("#0C3441")
    --palette_blue_2_900..base("#08222B")
    --palette_brand_100..base("#FFCCCC")
    --palette_brand_200..base("#FFB3B3")
    --palette_brand_300..base("#FF8080")
    --palette_brand_400..base("#FF5A5A")
    --palette_brand_50..base("#FFE5E6")
    --palette_brand_500..base("#FF3333")
    --palette_brand_600..base("#C20000")
    --palette_brand_700..base("#800000")
    --palette_brand_800..base("#5C0000")
    --palette_brand_900..base("#330000")
    --palette_green_100..base("#D6F5E3")
    --palette_green_200..base("#C2F0D5")
    --palette_green_300..base("#99E5B9")
    --palette_green_400..base("#71DB9D")
    --palette_green_50..base("#EBFAF1")
    --palette_green_500..base("#44CF7E")
    --palette_green_600..base("#29A35C")
    --palette_green_700..base("#1A6639")
    --palette_green_800..base("#0F3D22")
    --palette_green_900..base("#0A2917")
    --palette_grey_100..base("#EBEBEB")
    --palette_grey_200..base("#D9D9D9")
    --palette_grey_300..base("#C2C2C2")
    --palette_grey_400..base("#8C8C8C")
    --palette_grey_50..base("#FAFAFA")
    --palette_grey_500..base("#737373")
    --palette_grey_600..base("#616161")
    --palette_grey_700..base("#474747")
    --palette_grey_800..base("#333333")
    --palette_grey_900..base("#262626")
    --palette_grey_950..base("#1A1A1A")
    --palette_grey_990..base("#121212")
    --palette_orange_100..base("#FFE7CC")
    --palette_orange_200..base("#FFDBB3")
    --palette_orange_300..base("#FFC380")
    --palette_orange_400..base("#FFAB4C")
    --palette_orange_50..base("#FFF3E5")
    --palette_orange_500..base("#FF9114")
    --palette_orange_600..base("#CC6C00")
    --palette_orange_700..base("#804400")
    --palette_orange_800..base("#4D2900")
    --palette_orange_900..base("#331B00")
    --palette_red_100..base("#F7D4D4")
    --palette_red_200..base("#F2BFBF")
    --palette_red_300..base("#EA9495")
    --palette_red_400..base("#E26A6A")
    --palette_red_50..base("#FBEAEA")
    --palette_red_500..base("#D52A2A")
    --palette_red_600..base("#AA2222")
    --palette_red_700..base("#6B1515")
    --palette_red_800..base("#400D0D")
    --palette_red_900..base("#2B0808")
    --palette_red_2_100..base("#FECDCF")
    --palette_red_2_200..base("#FEB4B8")
    --palette_red_2_300..base("#FD8188")
    --palette_red_2_400..base("#FC5059")
    --palette_red_2_50..base("#FFE6E7")
    --palette_red_2_500..base("#FB3641")
    --palette_red_2_600..base("#FA0610")
    --palette_red_2_700..base("#96030A")
    --palette_red_2_800..base("#4B0105")
    --palette_red_2_900..base("#320103")
    --palette_white..base("#FFFFFF")
    --palette_yellow_100..base("#FEF4CE")
    --palette_yellow_200..base("#FFEBB3")
    --palette_yellow_300..base("#FFDD80")
    --palette_yellow_400..base("#FFCF4C")
    --palette_yellow_50..base("#FFF8E5")
    --palette_yellow_500..base("#FFC014")
    --palette_yellow_600..base("#CC9600")
    --palette_yellow_700..base("#805E00")
    --palette_yellow_800..base("#4D3800")
    --palette_yellow_900..base("#332500")
    --palette_yellow_2_100..base("#FFEECC")
    --palette_yellow_2_200..base("#FCEFB6")
    --palette_yellow_2_300..base("#FAE584")
    --palette_yellow_2_400..base("#FADB5C")
    --palette_yellow_2_50..base("#FEFAE6")
    --palette_yellow_2_500..base("#F8CE1E")
    --palette_yellow_2_600..base("#C4A209")
    --palette_yellow_2_700..base("#7B6506")
    --palette_yellow_2_800..base("#4A3D02")
    --palette_yellow_2_900..base("#322802")
    public static let typeDiasystBodyBold = TextStyle(name: Noir Pro, size: 16, weight: TextStyle.Weight(Bold), lineHeight: 23)
    public static let typeDiasystBodyHeavy = TextStyle(name: Noir Pro, size: 16, weight: TextStyle.Weight(Heavy), lineHeight: 23)
    public static let typeDiasystBodyLight = TextStyle(name: Noir Pro, size: 16, weight: TextStyle.Weight(Light), lineHeight: 23)
    public static let typeDiasystBodyMedium = TextStyle(name: Noir Pro, size: 16, weight: TextStyle.Weight(Medium), lineHeight: 23)
    public static let typeDiasystBodyRegular = TextStyle(name: Noir Pro, size: 16, weight: TextStyle.Weight(Regular), lineHeight: 23)
    public static let typeDiasystBodySemibold = TextStyle(name: Noir Pro, size: 16, weight: TextStyle.Weight(Semi Bold), lineHeight: 23)
    public static let typeDiasystCalloutBold = TextStyle(name: Noir Pro, size: 15, weight: TextStyle.Weight(Bold), lineHeight: 22)
    public static let typeDiasystCalloutHeavy = TextStyle(name: Noir Pro, size: 15, weight: TextStyle.Weight(Heavy), lineHeight: 22)
    public static let typeDiasystCalloutLight = TextStyle(name: Noir Pro, size: 15, weight: TextStyle.Weight(Light), lineHeight: 22)
    public static let typeDiasystCalloutMedium = TextStyle(name: Noir Pro, size: 15, weight: TextStyle.Weight(Medium), lineHeight: 22)
    public static let typeDiasystCalloutRegular = TextStyle(name: Noir Pro, size: 15, weight: TextStyle.Weight(Regular), lineHeight: 22)
    public static let typeDiasystCalloutSemibold = TextStyle(name: Noir Pro, size: 15, weight: TextStyle.Weight(Semi Bold), lineHeight: 22)
    public static let typeDiasystCaption1Bold = TextStyle(name: Noir Pro, size: 12, weight: TextStyle.Weight(Bold), lineHeight: 16)
    public static let typeDiasystCaption1Heavy = TextStyle(name: Noir Pro, size: 12, weight: TextStyle.Weight(Heavy), lineHeight: 16)
    public static let typeDiasystCaption1Light = TextStyle(name: Noir Pro, size: 12, weight: TextStyle.Weight(Light), lineHeight: 16)
    public static let typeDiasystCaption1Medium = TextStyle(name: Noir Pro, size: 12, weight: TextStyle.Weight(Medium), lineHeight: 16)
    public static let typeDiasystCaption1Regular = TextStyle(name: Noir Pro, size: 12, weight: TextStyle.Weight(Regular), lineHeight: 16)
    public static let typeDiasystCaption1Semibold = TextStyle(name: Noir Pro, size: 12, weight: TextStyle.Weight(Semi Bold), lineHeight: 16)
    public static let typeDiasystCaption2Bold = TextStyle(name: Noir Pro, size: 11, weight: TextStyle.Weight(Bold), lineHeight: 13)
    public static let typeDiasystCaption2Heavy = TextStyle(name: Noir Pro, size: 11, weight: TextStyle.Weight(Heavy), lineHeight: 13)
    public static let typeDiasystCaption2Light = TextStyle(name: Noir Pro, size: 11, weight: TextStyle.Weight(Light), lineHeight: 13)
    public static let typeDiasystCaption2Medium = TextStyle(name: Noir Pro, size: 11, weight: TextStyle.Weight(Medium), lineHeight: 13)
    public static let typeDiasystCaption2Regular = TextStyle(name: Noir Pro, size: 11, weight: TextStyle.Weight(Regular), lineHeight: 13)
    public static let typeDiasystCaption2Semibold = TextStyle(name: Noir Pro, size: 11, weight: TextStyle.Weight(Semi Bold), lineHeight: 13)
    public static let typeDiasystFootnoteBold = TextStyle(name: Noir Pro, size: 13, weight: TextStyle.Weight(Bold), lineHeight: 18)
    public static let typeDiasystFootnoteHeavy = TextStyle(name: Noir Pro, size: 13, weight: TextStyle.Weight(Heavy), lineHeight: 18)
    public static let typeDiasystFootnoteLight = TextStyle(name: Noir Pro, size: 13, weight: TextStyle.Weight(Light), lineHeight: 18)
    public static let typeDiasystFootnoteMedium = TextStyle(name: Noir Pro, size: 13, weight: TextStyle.Weight(Medium), lineHeight: 18)
    public static let typeDiasystFootnoteRegular = TextStyle(name: Noir Pro, size: 13, weight: TextStyle.Weight(Regular), lineHeight: 18)
    public static let typeDiasystFootnoteSemibold = TextStyle(name: Noir Pro, size: 13, weight: TextStyle.Weight(Semi Bold), lineHeight: 18)
    public static let typeDiasystHeadlineBold = TextStyle(name: Noir Pro, size: 18, weight: TextStyle.Weight(Bold), lineHeight: 25)
    public static let typeDiasystHeadlineHeavy = TextStyle(name: Noir Pro, size: 18, weight: TextStyle.Weight(Heavy), lineHeight: 25)
    public static let typeDiasystHeadlineLight = TextStyle(name: Noir Pro, size: 18, weight: TextStyle.Weight(Light), lineHeight: 25)
    public static let typeDiasystHeadlineMedium = TextStyle(name: Noir Pro, size: 18, weight: TextStyle.Weight(Medium), lineHeight: 25)
    public static let typeDiasystHeadlineRegular = TextStyle(name: Noir Pro, size: 18, weight: TextStyle.Weight(Regular), lineHeight: 25)
    public static let typeDiasystHeadlineSemibold = TextStyle(name: Noir Pro, size: 18, weight: TextStyle.Weight(Semi Bold), lineHeight: 25)
    public static let typeDiasystLargeBold = TextStyle(name: Noir Pro, size: 47, weight: TextStyle.Weight(Bold), lineHeight: 56)
    public static let typeDiasystLargeHeavy = TextStyle(name: Noir Pro, size: 47, weight: TextStyle.Weight(Heavy), lineHeight: 56)
    public static let typeDiasystLargeLight = TextStyle(name: Noir Pro, size: 47, weight: TextStyle.Weight(Light), lineHeight: 56)
    public static let typeDiasystLargeMedium = TextStyle(name: Noir Pro, size: 47, weight: TextStyle.Weight(Medium), lineHeight: 56)
    public static let typeDiasystLargeRegular = TextStyle(name: Noir Pro, size: 47, weight: TextStyle.Weight(Regular), lineHeight: 56)
    public static let typeDiasystLargeSemibold = TextStyle(name: Noir Pro, size: 47, weight: TextStyle.Weight(Semi Bold), lineHeight: 56)
    public static let typeDiasystSubheadlineBold = TextStyle(name: Noir Pro, size: 14, weight: TextStyle.Weight(Bold), lineHeight: 20)
    public static let typeDiasystSubheadlineHeavy = TextStyle(name: Noir Pro, size: 14, weight: TextStyle.Weight(Heavy), lineHeight: 20)
    public static let typeDiasystSubheadlineLight = TextStyle(name: Noir Pro, size: 14, weight: TextStyle.Weight(Light), lineHeight: 20)
    public static let typeDiasystSubheadlineMedium = TextStyle(name: Noir Pro, size: 14, weight: TextStyle.Weight(Medium), lineHeight: 20)
    public static let typeDiasystSubheadlineRegular = TextStyle(name: Noir Pro, size: 14, weight: TextStyle.Weight(Regular), lineHeight: 20)
    public static let typeDiasystSubheadlineSemibold = TextStyle(name: Noir Pro, size: 14, weight: TextStyle.Weight(Semi Bold), lineHeight: 20)
    public static let typeDiasystTitle1Bold = TextStyle(name: Noir Pro, size: 36, weight: TextStyle.Weight(Bold), lineHeight: 43)
    public static let typeDiasystTitle1Heavy = TextStyle(name: Noir Pro, size: 36, weight: TextStyle.Weight(Heavy), lineHeight: 43)
    public static let typeDiasystTitle1Light = TextStyle(name: Noir Pro, size: 36, weight: TextStyle.Weight(Light), lineHeight: 43)
    public static let typeDiasystTitle1Medium = TextStyle(name: Noir Pro, size: 36, weight: TextStyle.Weight(Medium), lineHeight: 43)
    public static let typeDiasystTitle1Regular = TextStyle(name: Noir Pro, size: 36, weight: TextStyle.Weight(Regular), lineHeight: 43)
    public static let typeDiasystTitle1Semibold = TextStyle(name: Noir Pro, size: 36, weight: TextStyle.Weight(Semi Bold), lineHeight: 43)
    public static let typeDiasystTitle2Bold = TextStyle(name: Noir Pro, size: 27, weight: TextStyle.Weight(Bold), lineHeight: 35)
    public static let typeDiasystTitle2Heavy = TextStyle(name: Noir Pro, size: 27, weight: TextStyle.Weight(Heavy), lineHeight: 35)
    public static let typeDiasystTitle2Light = TextStyle(name: Noir Pro, size: 27, weight: TextStyle.Weight(Light), lineHeight: 35)
    public static let typeDiasystTitle2Medium = TextStyle(name: Noir Pro, size: 27, weight: TextStyle.Weight(Medium), lineHeight: 35)
    public static let typeDiasystTitle2Regular = TextStyle(name: Noir Pro, size: 27, weight: TextStyle.Weight(Regular), lineHeight: 35)
    public static let typeDiasystTitle2Semibold = TextStyle(name: Noir Pro, size: 27, weight: TextStyle.Weight(Semi Bold), lineHeight: 35)
    public static let typeDiasystTitle3Bold = TextStyle(name: Noir Pro, size: 21, weight: TextStyle.Weight(Bold), lineHeight: 29)
    public static let typeDiasystTitle3Heavy = TextStyle(name: Noir Pro, size: 21, weight: TextStyle.Weight(Heavy), lineHeight: 29)
    public static let typeDiasystTitle3Light = TextStyle(name: Noir Pro, size: 21, weight: TextStyle.Weight(Light), lineHeight: 29)
    public static let typeDiasystTitle3Medium = TextStyle(name: Noir Pro, size: 21, weight: TextStyle.Weight(Medium), lineHeight: 29)
    public static let typeDiasystTitle3Regular = TextStyle(name: Noir Pro, size: 21, weight: TextStyle.Weight(Regular), lineHeight: 29)
    public static let typeDiasystTitle3Semibold = TextStyle(name: Noir Pro, size: 21, weight: TextStyle.Weight(Semi Bold), lineHeight: 29)
    public static let typeDiasystDefaultBody = TextStyle(name: Noir Pro, size: 16, weight: TextStyle.Weight(400), lineHeight: 23)
    public static let typeDiasystDefaultCallout = TextStyle(name: Noir Pro, size: 15, weight: TextStyle.Weight(400), lineHeight: 22)
    public static let typeDiasystDefaultCaption1 = TextStyle(name: Noir Pro, size: 12, weight: TextStyle.Weight(400), lineHeight: 16)
    public static let typeDiasystDefaultCaption2 = TextStyle(name: Noir Pro, size: 11, weight: TextStyle.Weight(400), lineHeight: 13)
    public static let typeDiasystDefaultFootnote = TextStyle(name: Noir Pro, size: 13, weight: TextStyle.Weight(500), lineHeight: 18)
    public static let typeDiasystDefaultHeadline = TextStyle(name: Noir Pro, size: 18, weight: TextStyle.Weight(500), lineHeight: 25)
    public static let typeDiasystDefaultLarge = TextStyle(name: Noir Pro, size: 47, weight: TextStyle.Weight(400), lineHeight: 56)
    public static let typeDiasystDefaultSubheadline = TextStyle(name: Noir Pro, size: 14, weight: TextStyle.Weight(400), lineHeight: 20)
    public static let typeDiasystDefaultTabitem = TextStyle(name: Noir Pro, size: 10, weight: TextStyle.Weight(500), lineHeight: 12)
    public static let typeDiasystDefaultTitle1 = TextStyle(name: Noir Pro, size: 36, weight: TextStyle.Weight(400), lineHeight: 43)
    public static let typeDiasystDefaultTitle2 = TextStyle(name: Noir Pro, size: 27, weight: TextStyle.Weight(400), lineHeight: 35)
    public static let typeDiasystDefaultTitle3 = TextStyle(name: Noir Pro, size: 21, weight: TextStyle.Weight(400), lineHeight: 29)
    public static let typeNormalBodyBold = TextStyle(name: SF Pro, size: 16, weight: TextStyle.Weight(Bold), lineHeight: 23)
    public static let typeNormalBodyHeavy = TextStyle(name: SF Pro, size: 16, weight: TextStyle.Weight(Heavy), lineHeight: 23)
    public static let typeNormalBodyLight = TextStyle(name: SF Pro, size: 16, weight: TextStyle.Weight(Light), lineHeight: 23)
    public static let typeNormalBodyMedium = TextStyle(name: SF Pro, size: 16, weight: TextStyle.Weight(Medium), lineHeight: 23)
    public static let typeNormalBodyRegular = TextStyle(name: SF Pro, size: 16, weight: TextStyle.Weight(Regular), lineHeight: 23)
    public static let typeNormalBodySemibold = TextStyle(name: SF Pro, size: 16, weight: TextStyle.Weight(Semibold), lineHeight: 23)
    public static let typeNormalCalloutBold = TextStyle(name: SF Pro, size: 15, weight: TextStyle.Weight(Bold), lineHeight: 22)
    public static let typeNormalCalloutHeavy = TextStyle(name: SF Pro, size: 15, weight: TextStyle.Weight(Heavy), lineHeight: 22)
    public static let typeNormalCalloutLight = TextStyle(name: SF Pro, size: 15, weight: TextStyle.Weight(Light), lineHeight: 22)
    public static let typeNormalCalloutMedium = TextStyle(name: SF Pro, size: 15, weight: TextStyle.Weight(Medium), lineHeight: 22)
    public static let typeNormalCalloutRegular = TextStyle(name: SF Pro, size: 15, weight: TextStyle.Weight(Regular), lineHeight: 22)
    public static let typeNormalCalloutSemibold = TextStyle(name: SF Pro, size: 15, weight: TextStyle.Weight(Semibold), lineHeight: 22)
    public static let typeNormalCaption1Bold = TextStyle(name: SF Pro, size: 12, weight: TextStyle.Weight(Bold), lineHeight: 16)
    public static let typeNormalCaption1Heavy = TextStyle(name: SF Pro, size: 12, weight: TextStyle.Weight(Heavy), lineHeight: 16)
    public static let typeNormalCaption1Light = TextStyle(name: SF Pro, size: 12, weight: TextStyle.Weight(Light), lineHeight: 16)
    public static let typeNormalCaption1Medium = TextStyle(name: SF Pro, size: 12, weight: TextStyle.Weight(Medium), lineHeight: 16)
    public static let typeNormalCaption1Regular = TextStyle(name: SF Pro, size: 12, weight: TextStyle.Weight(Regular), lineHeight: 16)
    public static let typeNormalCaption1Semibold = TextStyle(name: SF Pro, size: 12, weight: TextStyle.Weight(Semibold), lineHeight: 16)
    public static let typeNormalCaption2Bold = TextStyle(name: SF Pro, size: 11, weight: TextStyle.Weight(Bold), lineHeight: 13)
    public static let typeNormalCaption2Heavy = TextStyle(name: SF Pro, size: 11, weight: TextStyle.Weight(Heavy), lineHeight: 13)
    public static let typeNormalCaption2Light = TextStyle(name: SF Pro, size: 11, weight: TextStyle.Weight(Light), lineHeight: 13)
    public static let typeNormalCaption2Medium = TextStyle(name: SF Pro, size: 11, weight: TextStyle.Weight(Medium), lineHeight: 13)
    public static let typeNormalCaption2Regular = TextStyle(name: SF Pro, size: 11, weight: TextStyle.Weight(Regular), lineHeight: 13)
    public static let typeNormalCaption2Semibold = TextStyle(name: SF Pro, size: 11, weight: TextStyle.Weight(Semibold), lineHeight: 13)
    public static let typeNormalFootnoteBold = TextStyle(name: SF Pro, size: 13, weight: TextStyle.Weight(Bold), lineHeight: 18)
    public static let typeNormalFootnoteHeavy = TextStyle(name: SF Pro, size: 13, weight: TextStyle.Weight(Heavy), lineHeight: 18)
    public static let typeNormalFootnoteLight = TextStyle(name: SF Pro, size: 13, weight: TextStyle.Weight(Light), lineHeight: 18)
    public static let typeNormalFootnoteMedium = TextStyle(name: SF Pro, size: 13, weight: TextStyle.Weight(Medium), lineHeight: 18)
    public static let typeNormalFootnoteRegular = TextStyle(name: SF Pro, size: 13, weight: TextStyle.Weight(Regular), lineHeight: 18)
    public static let typeNormalFootnoteSemibold = TextStyle(name: SF Pro, size: 13, weight: TextStyle.Weight(Semibold), lineHeight: 18)
    public static let typeNormalHeadlineBold = TextStyle(name: SF Pro, size: 18, weight: TextStyle.Weight(Bold), lineHeight: 25)
    public static let typeNormalHeadlineHeavy = TextStyle(name: SF Pro, size: 18, weight: TextStyle.Weight(Heavy), lineHeight: 25)
    public static let typeNormalHeadlineLight = TextStyle(name: SF Pro, size: 18, weight: TextStyle.Weight(Light), lineHeight: 25)
    public static let typeNormalHeadlineMedium = TextStyle(name: SF Pro, size: 18, weight: TextStyle.Weight(Medium), lineHeight: 25)
    public static let typeNormalHeadlineRegular = TextStyle(name: SF Pro, size: 18, weight: TextStyle.Weight(Regular), lineHeight: 25)
    public static let typeNormalHeadlineSemibold = TextStyle(name: SF Pro, size: 18, weight: TextStyle.Weight(Semibold), lineHeight: 25)
    public static let typeNormalLargeBold = TextStyle(name: SF Pro, size: 47, weight: TextStyle.Weight(Bold), lineHeight: 56)
    public static let typeNormalLargeHeavy = TextStyle(name: SF Pro, size: 47, weight: TextStyle.Weight(Heavy), lineHeight: 56)
    public static let typeNormalLargeLight = TextStyle(name: SF Pro, size: 47, weight: TextStyle.Weight(Light), lineHeight: 56)
    public static let typeNormalLargeMedium = TextStyle(name: SF Pro, size: 47, weight: TextStyle.Weight(Medium), lineHeight: 56)
    public static let typeNormalLargeRegular = TextStyle(name: SF Pro, size: 47, weight: TextStyle.Weight(Regular), lineHeight: 56)
    public static let typeNormalLargeSemibold = TextStyle(name: SF Pro, size: 47, weight: TextStyle.Weight(Semibold), lineHeight: 56)
    public static let typeNormalSubheadlineBold = TextStyle(name: SF Pro, size: 14, weight: TextStyle.Weight(Bold), lineHeight: 20)
    public static let typeNormalSubheadlineHeavy = TextStyle(name: SF Pro, size: 14, weight: TextStyle.Weight(Heavy), lineHeight: 20)
    public static let typeNormalSubheadlineLight = TextStyle(name: SF Pro, size: 14, weight: TextStyle.Weight(Light), lineHeight: 20)
    public static let typeNormalSubheadlineMedium = TextStyle(name: SF Pro, size: 14, weight: TextStyle.Weight(Medium), lineHeight: 20)
    public static let typeNormalSubheadlineRegular = TextStyle(name: SF Pro, size: 14, weight: TextStyle.Weight(Regular), lineHeight: 20)
    public static let typeNormalSubheadlineSemibold = TextStyle(name: SF Pro, size: 14, weight: TextStyle.Weight(Semibold), lineHeight: 20)
    public static let typeNormalTitle1Bold = TextStyle(name: SF Pro, size: 36, weight: TextStyle.Weight(Bold), lineHeight: 43)
    public static let typeNormalTitle1Heavy = TextStyle(name: SF Pro, size: 36, weight: TextStyle.Weight(Heavy), lineHeight: 43)
    public static let typeNormalTitle1Light = TextStyle(name: SF Pro, size: 36, weight: TextStyle.Weight(Light), lineHeight: 43)
    public static let typeNormalTitle1Medium = TextStyle(name: SF Pro, size: 36, weight: TextStyle.Weight(Medium), lineHeight: 43)
    public static let typeNormalTitle1Regular = TextStyle(name: SF Pro, size: 36, weight: TextStyle.Weight(Regular), lineHeight: 43)
    public static let typeNormalTitle1Semibold = TextStyle(name: SF Pro, size: 36, weight: TextStyle.Weight(Semibold), lineHeight: 43)
    public static let typeNormalTitle2Bold = TextStyle(name: SF Pro, size: 27, weight: TextStyle.Weight(Bold), lineHeight: 35)
    public static let typeNormalTitle2Heavy = TextStyle(name: SF Pro, size: 27, weight: TextStyle.Weight(Heavy), lineHeight: 35)
    public static let typeNormalTitle2Light = TextStyle(name: SF Pro, size: 27, weight: TextStyle.Weight(Light), lineHeight: 35)
    public static let typeNormalTitle2Medium = TextStyle(name: SF Pro, size: 27, weight: TextStyle.Weight(Medium), lineHeight: 35)
    public static let typeNormalTitle2Regular = TextStyle(name: SF Pro, size: 27, weight: TextStyle.Weight(Regular), lineHeight: 35)
    public static let typeNormalTitle2Semibold = TextStyle(name: SF Pro, size: 27, weight: TextStyle.Weight(Semibold), lineHeight: 35)
    public static let typeNormalTitle3Bold = TextStyle(name: SF Pro, size: 21, weight: TextStyle.Weight(Bold), lineHeight: 29)
    public static let typeNormalTitle3Heavy = TextStyle(name: SF Pro, size: 21, weight: TextStyle.Weight(Heavy), lineHeight: 29)
    public static let typeNormalTitle3Light = TextStyle(name: SF Pro, size: 21, weight: TextStyle.Weight(Light), lineHeight: 29)
    public static let typeNormalTitle3Medium = TextStyle(name: SF Pro, size: 21, weight: TextStyle.Weight(Medium), lineHeight: 29)
    public static let typeNormalTitle3Regular = TextStyle(name: SF Pro, size: 21, weight: TextStyle.Weight(Regular), lineHeight: 29)
    public static let typeNormalTitle3Semibold = TextStyle(name: SF Pro, size: 21, weight: TextStyle.Weight(Semibold), lineHeight: 29)
    public static let typeNormalDefaultBody = TextStyle(name: SF Pro, size: 16, weight: TextStyle.Weight(400), lineHeight: 23)
    public static let typeNormalDefaultCallout = TextStyle(name: SF Pro, size: 15, weight: TextStyle.Weight(400), lineHeight: 22)
    public static let typeNormalDefaultCaption1 = TextStyle(name: SF Pro, size: 12, weight: TextStyle.Weight(400), lineHeight: 16)
    public static let typeNormalDefaultCaption2 = TextStyle(name: SF Pro, size: 11, weight: TextStyle.Weight(400), lineHeight: 13)
    public static let typeNormalDefaultFootnote = TextStyle(name: SF Pro, size: 13, weight: TextStyle.Weight(600), lineHeight: 18)
    public static let typeNormalDefaultHeadline = TextStyle(name: SF Pro, size: 18, weight: TextStyle.Weight(600), lineHeight: 25)
    public static let typeNormalDefaultLarge = TextStyle(name: SF Pro, size: 47, weight: TextStyle.Weight(400), lineHeight: 56)
    public static let typeNormalDefaultSubheadline = TextStyle(name: SF Pro, size: 14, weight: TextStyle.Weight(400), lineHeight: 20)
    public static let typeNormalDefaultTitle1 = TextStyle(name: SF Pro, size: 36, weight: TextStyle.Weight(400), lineHeight: 43)
    public static let typeNormalDefaultTitle2 = TextStyle(name: SF Pro, size: 27, weight: TextStyle.Weight(400), lineHeight: 35)
    public static let typeNormalDefaultTitle3 = TextStyle(name: SF Pro, size: 21, weight: TextStyle.Weight(400), lineHeight: 29)
    public static let core_space_1 = CGFloat(4)
    public static let core_space_10 = CGFloat(40)
    public static let core_space_11 = CGFloat(44)
    public static let core_space_12 = CGFloat(48)
    public static let core_space_14 = CGFloat(56)
    public static let core_space_16 = CGFloat(64)
    public static let core_space_2 = CGFloat(8)
    public static let core_space_20 = CGFloat(80)
    public static let core_space_24 = CGFloat(96)
    public static let core_space_28 = CGFloat(112)
    public static let core_space_3 = CGFloat(12)
    public static let core_space_32 = CGFloat(128)
    public static let core_space_36 = CGFloat(144)
    public static let core_space_4 = CGFloat(16)
    public static let core_space_40 = CGFloat(160)
    public static let core_space_48 = CGFloat(192)
    public static let core_space_5 = CGFloat(20)
    public static let core_space_52 = CGFloat(208)
    public static let core_space_56 = CGFloat(224)
    public static let core_space_6 = CGFloat(24)
    public static let core_space_60 = CGFloat(240)
    public static let core_space_64 = CGFloat(256)
    public static let core_space_7 = CGFloat(28)
    public static let core_space_72 = CGFloat(288)
    public static let core_space_8 = CGFloat(32)
    public static let core_space_80 = CGFloat(320)
    public static let core_space_9 = CGFloat(36)
    public static let core_space_96 = CGFloat(384)
    public static let core_space_half = CGFloat(2)
    public static let core_space_px = CGFloat(1)
    public static let core_space_zero = CGFloat(0)
    public static let core_border_base = CGFloat(0.33)
    public static let core_border_bold = CGFloat(2)
    public static let core_border_md = CGFloat(1.5)
    public static let core_border_sm = CGFloat(1.0)
    public static let form_input_active = CGFloat(2)
    public static let form_input_normal = CGFloat(1.0)
    public static let core_border_radius_1 = CGFloat(4)
    public static let core_border_radius_10 = CGFloat(40)
    public static let core_border_radius_2 = CGFloat(8)
    public static let core_border_radius_3 = CGFloat(12)
    public static let core_border_radius_4 = CGFloat(16)
    public static let core_border_radius_5 = CGFloat(20)
    public static let core_border_radius_6 = CGFloat(24)
    public static let core_border_radius_7 = CGFloat(28)
    public static let core_border_radius_8 = CGFloat(32)
    public static let core_border_radius_9 = CGFloat(36)
    public static let core_border_radius_half = CGFloat(2)
    public static let core_border_radius_px = CGFloat(1)
    public static let core_border_radius_zero = CGFloat(0)
    public static let letterSpacingBody = CGFloat(-0.41)
    public static let letterSpacingCallout = CGFloat(-0.32)
    public static let letterSpacingCaption1 = CGFloat(0)
    public static let letterSpacingCaption2 = CGFloat(0.07)
    public static let letterSpacingFootnote = CGFloat(-0.08)
    public static let letterSpacingHeadline = CGFloat(-0.41)
    public static let letterSpacingLarge = CGFloat(0.37)
    public static let letterSpacingSubheadline = CGFloat(-0.24)
    public static let letterSpacingTitle1 = CGFloat(0.36)
    public static let letterSpacingTitle2 = CGFloat(0.35)
    public static let letterSpacingTitle3 = CGFloat(0.38)
    public static let font_size_body = CGFloat(16)
    public static let font_size_callout = CGFloat(15)
    public static let font_size_caption_1 = CGFloat(12)
    public static let font_size_caption_2 = CGFloat(11)
    public static let font_size_footnote = CGFloat(13)
    public static let font_size_headline = CGFloat(18)
    public static let font_size_large = CGFloat(47)
    public static let font_size_subheadline = CGFloat(14)
    public static let font_size_title_1 = CGFloat(36)
    public static let font_size_title_2 = CGFloat(27)
    public static let font_size_title_3 = CGFloat(21)
    public static let font_weight_black = CGFloat(900)
    public static let font_weight_bold = CGFloat(700)
    public static let font_weight_heavy = CGFloat(800)
    public static let font_weight_light = CGFloat(300)
    public static let font_weight_medium = CGFloat(500)
    public static let font_weight_regular = CGFloat(400)
    public static let font_weight_semibold = CGFloat(600)
    public static let font_name_diasyst = CGFloat(Noir Pro)
    public static let font_name_normal = CGFloat(SF Pro)
    public static let font_lineheight_body = CGFloat(23)
    public static let font_lineheight_callout = CGFloat(22)
    public static let font_lineheight_caption_1 = CGFloat(16)
    public static let font_lineheight_caption_2 = CGFloat(13)
    public static let font_lineheight_footnote = CGFloat(18)
    public static let font_lineheight_headline = CGFloat(25)
    public static let font_lineheight_large = CGFloat(56)
    public static let font_lineheight_subheadline = CGFloat(20)
    public static let font_lineheight_title_1 = CGFloat(43)
    public static let font_lineheight_title_2 = CGFloat(35)
    public static let font_lineheight_title_3 = CGFloat(29)
    public static let shadow_popup_1 = Shadow("#00000026")
    public static let shadow_reg_home_card = Shadow("#0000003F")
    public static let shadow_tab_bar = Shadow("#00000019")
    public static let shadow_popup_1 = Shadow("#00000026", "#00000026")
    public static let shadow_reg_home_card = Shadow("#0000003F", "#0000003F")
    public static let shadow_tab_bar = Shadow("#00000019", "#00000019")
    
    


}
