version: 2.1
orbs:
  win: circleci/windows@5.0 
jobs:
  build:
    executor: win/server-2022 
    docker:
      - image: cimg/rust:1.72.1
    steps:
      - checkout
      - run: Write-Host 'Start the Process'
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test"
