global:
  # Other files will be merged togehter
  other_path: 
    - value: 
      - "assets/figma/core.json"
      - "assets/figma/typography.json"
      - "assets/figma/global.json"
    - value: 
      - "assets/figma/mobile.json"
  # Styles will be kept separate
  style_path:
    - "assets/figma/dark.json"
    - "assets/figma/light.json"
  # Output path 
  style_output_path: "assets/generated_styles"
templates:
  - settings_general:
      generate_file_path: "generated_templates"
      file_name:
        format: "cds-{style}"
        extension: "css"
        case: "kebab"
        #This will replace the class_name from template_type as well
        #use_as_class_name: true
    settings_custom:
      header: ":root {"
      #sub_header: "test sub header"
      #sub_footer: "test sub footer"
      footer: "}"
      # Only if class is set, class_name will be displayed
      #class: "public class"
      #class_name: "DSCore{style}"
      template_type:
        - type: color
          value: "--{{variable_name | kebab}} {{color | color: 'rgb_r_v1, rgb_g_v2'}};"
        - type: composition
          value: "{% if verticalPadding != '' %} test1: {{verticalPadding | optional: 'vertical-padding-test-first: %value'}} {% endif %}"
        - type: composition
          value: "{% if verticalPadding != '' %} test2: {{verticalPadding | optional: 'vartical-padding-test-second: %value'}} {% endif %}"
        - type: boxShadow
          value: 
            - "{{variable_name}} {{color-0 | color: 'hex'}} blur: {{blur-0}} x: {{x-0}}"
            - "{{variable_name}} {{color-0 | color: 'hex'}} {{color-1 | color: 'hex'}}  blur: {{blur-0}} x: {{x-0}} blur: {{blur-1}} x: {{x-1}}"
